//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace BusinessLayerLogic.openligadb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SportsdataSoap", Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Sportsdata : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAvailLeaguesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNextMatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastMatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentGroupOrderIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchdataByGroupLeagueSaisonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchdataByLeagueDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchdataByTeamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchdataByLeagueSaisonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchdataByGroupLeagueSaisonJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFusballdatenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatchByMatchIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamsByLeagueSaisonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailSportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailLeaguesBySportsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Sportsdata() {
            this.Url = global::BusinessLayerLogic.Properties.Settings.Default.BusinessLayerLogic_openligadb_Sportsdata;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAvailLeaguesCompletedEventHandler GetAvailLeaguesCompleted;
        
        /// <remarks/>
        public event GetNextMatchCompletedEventHandler GetNextMatchCompleted;
        
        /// <remarks/>
        public event GetLastMatchCompletedEventHandler GetLastMatchCompleted;
        
        /// <remarks/>
        public event GetCurrentGroupOrderIDCompletedEventHandler GetCurrentGroupOrderIDCompleted;
        
        /// <remarks/>
        public event GetMatchdataByGroupLeagueSaisonCompletedEventHandler GetMatchdataByGroupLeagueSaisonCompleted;
        
        /// <remarks/>
        public event GetMatchdataByLeagueDateTimeCompletedEventHandler GetMatchdataByLeagueDateTimeCompleted;
        
        /// <remarks/>
        public event GetMatchdataByTeamsCompletedEventHandler GetMatchdataByTeamsCompleted;
        
        /// <remarks/>
        public event GetMatchdataByLeagueSaisonCompletedEventHandler GetMatchdataByLeagueSaisonCompleted;
        
        /// <remarks/>
        public event GetMatchdataByGroupLeagueSaisonJSONCompletedEventHandler GetMatchdataByGroupLeagueSaisonJSONCompleted;
        
        /// <remarks/>
        public event GetFusballdatenCompletedEventHandler GetFusballdatenCompleted;
        
        /// <remarks/>
        public event GetMatchByMatchIDCompletedEventHandler GetMatchByMatchIDCompleted;
        
        /// <remarks/>
        public event GetTeamsByLeagueSaisonCompletedEventHandler GetTeamsByLeagueSaisonCompleted;
        
        /// <remarks/>
        public event GetAvailGroupsCompletedEventHandler GetAvailGroupsCompleted;
        
        /// <remarks/>
        public event GetAvailSportsCompletedEventHandler GetAvailSportsCompleted;
        
        /// <remarks/>
        public event GetAvailLeaguesBySportsCompletedEventHandler GetAvailLeaguesBySportsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetAvailLeagues", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public League[] GetAvailLeagues() {
            object[] results = this.Invoke("GetAvailLeagues", new object[0]);
            return ((League[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailLeaguesAsync() {
            this.GetAvailLeaguesAsync(null);
        }
        
        /// <remarks/>
        public void GetAvailLeaguesAsync(object userState) {
            if ((this.GetAvailLeaguesOperationCompleted == null)) {
                this.GetAvailLeaguesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailLeaguesOperationCompleted);
            }
            this.InvokeAsync("GetAvailLeagues", new object[0], this.GetAvailLeaguesOperationCompleted, userState);
        }
        
        private void OnGetAvailLeaguesOperationCompleted(object arg) {
            if ((this.GetAvailLeaguesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailLeaguesCompleted(this, new GetAvailLeaguesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetNextMatch", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Matchdata GetNextMatch(string leagueShortcut) {
            object[] results = this.Invoke("GetNextMatch", new object[] {
                        leagueShortcut});
            return ((Matchdata)(results[0]));
        }
        
        /// <remarks/>
        public void GetNextMatchAsync(string leagueShortcut) {
            this.GetNextMatchAsync(leagueShortcut, null);
        }
        
        /// <remarks/>
        public void GetNextMatchAsync(string leagueShortcut, object userState) {
            if ((this.GetNextMatchOperationCompleted == null)) {
                this.GetNextMatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNextMatchOperationCompleted);
            }
            this.InvokeAsync("GetNextMatch", new object[] {
                        leagueShortcut}, this.GetNextMatchOperationCompleted, userState);
        }
        
        private void OnGetNextMatchOperationCompleted(object arg) {
            if ((this.GetNextMatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNextMatchCompleted(this, new GetNextMatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetLastMatch", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Matchdata GetLastMatch(string leagueShortcut) {
            object[] results = this.Invoke("GetLastMatch", new object[] {
                        leagueShortcut});
            return ((Matchdata)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastMatchAsync(string leagueShortcut) {
            this.GetLastMatchAsync(leagueShortcut, null);
        }
        
        /// <remarks/>
        public void GetLastMatchAsync(string leagueShortcut, object userState) {
            if ((this.GetLastMatchOperationCompleted == null)) {
                this.GetLastMatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastMatchOperationCompleted);
            }
            this.InvokeAsync("GetLastMatch", new object[] {
                        leagueShortcut}, this.GetLastMatchOperationCompleted, userState);
        }
        
        private void OnGetLastMatchOperationCompleted(object arg) {
            if ((this.GetLastMatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastMatchCompleted(this, new GetLastMatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetCurrentGroupOrderID", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCurrentGroupOrderID(string leagueShortcut) {
            object[] results = this.Invoke("GetCurrentGroupOrderID", new object[] {
                        leagueShortcut});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentGroupOrderIDAsync(string leagueShortcut) {
            this.GetCurrentGroupOrderIDAsync(leagueShortcut, null);
        }
        
        /// <remarks/>
        public void GetCurrentGroupOrderIDAsync(string leagueShortcut, object userState) {
            if ((this.GetCurrentGroupOrderIDOperationCompleted == null)) {
                this.GetCurrentGroupOrderIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentGroupOrderIDOperationCompleted);
            }
            this.InvokeAsync("GetCurrentGroupOrderID", new object[] {
                        leagueShortcut}, this.GetCurrentGroupOrderIDOperationCompleted, userState);
        }
        
        private void OnGetCurrentGroupOrderIDOperationCompleted(object arg) {
            if ((this.GetCurrentGroupOrderIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentGroupOrderIDCompleted(this, new GetCurrentGroupOrderIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetMatchdataByGroupLeagueSaison", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Matchdata[] GetMatchdataByGroupLeagueSaison(int groupOrderID, string leagueShortcut, string leagueSaison) {
            object[] results = this.Invoke("GetMatchdataByGroupLeagueSaison", new object[] {
                        groupOrderID,
                        leagueShortcut,
                        leagueSaison});
            return ((Matchdata[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchdataByGroupLeagueSaisonAsync(int groupOrderID, string leagueShortcut, string leagueSaison) {
            this.GetMatchdataByGroupLeagueSaisonAsync(groupOrderID, leagueShortcut, leagueSaison, null);
        }
        
        /// <remarks/>
        public void GetMatchdataByGroupLeagueSaisonAsync(int groupOrderID, string leagueShortcut, string leagueSaison, object userState) {
            if ((this.GetMatchdataByGroupLeagueSaisonOperationCompleted == null)) {
                this.GetMatchdataByGroupLeagueSaisonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchdataByGroupLeagueSaisonOperationCompleted);
            }
            this.InvokeAsync("GetMatchdataByGroupLeagueSaison", new object[] {
                        groupOrderID,
                        leagueShortcut,
                        leagueSaison}, this.GetMatchdataByGroupLeagueSaisonOperationCompleted, userState);
        }
        
        private void OnGetMatchdataByGroupLeagueSaisonOperationCompleted(object arg) {
            if ((this.GetMatchdataByGroupLeagueSaisonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchdataByGroupLeagueSaisonCompleted(this, new GetMatchdataByGroupLeagueSaisonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetMatchdataByLeagueDateTime", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Matchdata[] GetMatchdataByLeagueDateTime(System.DateTime fromDateTime, System.DateTime toDateTime, string leagueShortcut) {
            object[] results = this.Invoke("GetMatchdataByLeagueDateTime", new object[] {
                        fromDateTime,
                        toDateTime,
                        leagueShortcut});
            return ((Matchdata[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchdataByLeagueDateTimeAsync(System.DateTime fromDateTime, System.DateTime toDateTime, string leagueShortcut) {
            this.GetMatchdataByLeagueDateTimeAsync(fromDateTime, toDateTime, leagueShortcut, null);
        }
        
        /// <remarks/>
        public void GetMatchdataByLeagueDateTimeAsync(System.DateTime fromDateTime, System.DateTime toDateTime, string leagueShortcut, object userState) {
            if ((this.GetMatchdataByLeagueDateTimeOperationCompleted == null)) {
                this.GetMatchdataByLeagueDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchdataByLeagueDateTimeOperationCompleted);
            }
            this.InvokeAsync("GetMatchdataByLeagueDateTime", new object[] {
                        fromDateTime,
                        toDateTime,
                        leagueShortcut}, this.GetMatchdataByLeagueDateTimeOperationCompleted, userState);
        }
        
        private void OnGetMatchdataByLeagueDateTimeOperationCompleted(object arg) {
            if ((this.GetMatchdataByLeagueDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchdataByLeagueDateTimeCompleted(this, new GetMatchdataByLeagueDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetMatchdataByTeams", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Matchdata[] GetMatchdataByTeams(int teamID1, int teamID2) {
            object[] results = this.Invoke("GetMatchdataByTeams", new object[] {
                        teamID1,
                        teamID2});
            return ((Matchdata[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchdataByTeamsAsync(int teamID1, int teamID2) {
            this.GetMatchdataByTeamsAsync(teamID1, teamID2, null);
        }
        
        /// <remarks/>
        public void GetMatchdataByTeamsAsync(int teamID1, int teamID2, object userState) {
            if ((this.GetMatchdataByTeamsOperationCompleted == null)) {
                this.GetMatchdataByTeamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchdataByTeamsOperationCompleted);
            }
            this.InvokeAsync("GetMatchdataByTeams", new object[] {
                        teamID1,
                        teamID2}, this.GetMatchdataByTeamsOperationCompleted, userState);
        }
        
        private void OnGetMatchdataByTeamsOperationCompleted(object arg) {
            if ((this.GetMatchdataByTeamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchdataByTeamsCompleted(this, new GetMatchdataByTeamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetMatchdataByLeagueSaison", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Matchdata[] GetMatchdataByLeagueSaison(string leagueShortcut, string leagueSaison) {
            object[] results = this.Invoke("GetMatchdataByLeagueSaison", new object[] {
                        leagueShortcut,
                        leagueSaison});
            return ((Matchdata[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchdataByLeagueSaisonAsync(string leagueShortcut, string leagueSaison) {
            this.GetMatchdataByLeagueSaisonAsync(leagueShortcut, leagueSaison, null);
        }
        
        /// <remarks/>
        public void GetMatchdataByLeagueSaisonAsync(string leagueShortcut, string leagueSaison, object userState) {
            if ((this.GetMatchdataByLeagueSaisonOperationCompleted == null)) {
                this.GetMatchdataByLeagueSaisonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchdataByLeagueSaisonOperationCompleted);
            }
            this.InvokeAsync("GetMatchdataByLeagueSaison", new object[] {
                        leagueShortcut,
                        leagueSaison}, this.GetMatchdataByLeagueSaisonOperationCompleted, userState);
        }
        
        private void OnGetMatchdataByLeagueSaisonOperationCompleted(object arg) {
            if ((this.GetMatchdataByLeagueSaisonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchdataByLeagueSaisonCompleted(this, new GetMatchdataByLeagueSaisonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetMatchdataByGroupLeagueSaisonJSON", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMatchdataByGroupLeagueSaisonJSON(int groupOrderID, string leagueShortcut, string leagueSaison) {
            object[] results = this.Invoke("GetMatchdataByGroupLeagueSaisonJSON", new object[] {
                        groupOrderID,
                        leagueShortcut,
                        leagueSaison});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchdataByGroupLeagueSaisonJSONAsync(int groupOrderID, string leagueShortcut, string leagueSaison) {
            this.GetMatchdataByGroupLeagueSaisonJSONAsync(groupOrderID, leagueShortcut, leagueSaison, null);
        }
        
        /// <remarks/>
        public void GetMatchdataByGroupLeagueSaisonJSONAsync(int groupOrderID, string leagueShortcut, string leagueSaison, object userState) {
            if ((this.GetMatchdataByGroupLeagueSaisonJSONOperationCompleted == null)) {
                this.GetMatchdataByGroupLeagueSaisonJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchdataByGroupLeagueSaisonJSONOperationCompleted);
            }
            this.InvokeAsync("GetMatchdataByGroupLeagueSaisonJSON", new object[] {
                        groupOrderID,
                        leagueShortcut,
                        leagueSaison}, this.GetMatchdataByGroupLeagueSaisonJSONOperationCompleted, userState);
        }
        
        private void OnGetMatchdataByGroupLeagueSaisonJSONOperationCompleted(object arg) {
            if ((this.GetMatchdataByGroupLeagueSaisonJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchdataByGroupLeagueSaisonJSONCompleted(this, new GetMatchdataByGroupLeagueSaisonJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetFusballdaten", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Fussballdaten[] GetFusballdaten(int Spieltag, string Liga, int Saison, string Userkennung) {
            object[] results = this.Invoke("GetFusballdaten", new object[] {
                        Spieltag,
                        Liga,
                        Saison,
                        Userkennung});
            return ((Fussballdaten[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFusballdatenAsync(int Spieltag, string Liga, int Saison, string Userkennung) {
            this.GetFusballdatenAsync(Spieltag, Liga, Saison, Userkennung, null);
        }
        
        /// <remarks/>
        public void GetFusballdatenAsync(int Spieltag, string Liga, int Saison, string Userkennung, object userState) {
            if ((this.GetFusballdatenOperationCompleted == null)) {
                this.GetFusballdatenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFusballdatenOperationCompleted);
            }
            this.InvokeAsync("GetFusballdaten", new object[] {
                        Spieltag,
                        Liga,
                        Saison,
                        Userkennung}, this.GetFusballdatenOperationCompleted, userState);
        }
        
        private void OnGetFusballdatenOperationCompleted(object arg) {
            if ((this.GetFusballdatenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFusballdatenCompleted(this, new GetFusballdatenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetMatchByMatchID", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Matchdata GetMatchByMatchID(int MatchID) {
            object[] results = this.Invoke("GetMatchByMatchID", new object[] {
                        MatchID});
            return ((Matchdata)(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchByMatchIDAsync(int MatchID) {
            this.GetMatchByMatchIDAsync(MatchID, null);
        }
        
        /// <remarks/>
        public void GetMatchByMatchIDAsync(int MatchID, object userState) {
            if ((this.GetMatchByMatchIDOperationCompleted == null)) {
                this.GetMatchByMatchIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchByMatchIDOperationCompleted);
            }
            this.InvokeAsync("GetMatchByMatchID", new object[] {
                        MatchID}, this.GetMatchByMatchIDOperationCompleted, userState);
        }
        
        private void OnGetMatchByMatchIDOperationCompleted(object arg) {
            if ((this.GetMatchByMatchIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchByMatchIDCompleted(this, new GetMatchByMatchIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetTeamsByLeagueSaison", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Team[] GetTeamsByLeagueSaison(string leagueShortcut, string leagueSaison) {
            object[] results = this.Invoke("GetTeamsByLeagueSaison", new object[] {
                        leagueShortcut,
                        leagueSaison});
            return ((Team[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamsByLeagueSaisonAsync(string leagueShortcut, string leagueSaison) {
            this.GetTeamsByLeagueSaisonAsync(leagueShortcut, leagueSaison, null);
        }
        
        /// <remarks/>
        public void GetTeamsByLeagueSaisonAsync(string leagueShortcut, string leagueSaison, object userState) {
            if ((this.GetTeamsByLeagueSaisonOperationCompleted == null)) {
                this.GetTeamsByLeagueSaisonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamsByLeagueSaisonOperationCompleted);
            }
            this.InvokeAsync("GetTeamsByLeagueSaison", new object[] {
                        leagueShortcut,
                        leagueSaison}, this.GetTeamsByLeagueSaisonOperationCompleted, userState);
        }
        
        private void OnGetTeamsByLeagueSaisonOperationCompleted(object arg) {
            if ((this.GetTeamsByLeagueSaisonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamsByLeagueSaisonCompleted(this, new GetTeamsByLeagueSaisonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetAvailGroups", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Group[] GetAvailGroups(string leagueShortcut, string leagueSaison) {
            object[] results = this.Invoke("GetAvailGroups", new object[] {
                        leagueShortcut,
                        leagueSaison});
            return ((Group[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailGroupsAsync(string leagueShortcut, string leagueSaison) {
            this.GetAvailGroupsAsync(leagueShortcut, leagueSaison, null);
        }
        
        /// <remarks/>
        public void GetAvailGroupsAsync(string leagueShortcut, string leagueSaison, object userState) {
            if ((this.GetAvailGroupsOperationCompleted == null)) {
                this.GetAvailGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailGroupsOperationCompleted);
            }
            this.InvokeAsync("GetAvailGroups", new object[] {
                        leagueShortcut,
                        leagueSaison}, this.GetAvailGroupsOperationCompleted, userState);
        }
        
        private void OnGetAvailGroupsOperationCompleted(object arg) {
            if ((this.GetAvailGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailGroupsCompleted(this, new GetAvailGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetAvailSports", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Sports[] GetAvailSports() {
            object[] results = this.Invoke("GetAvailSports", new object[0]);
            return ((Sports[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailSportsAsync() {
            this.GetAvailSportsAsync(null);
        }
        
        /// <remarks/>
        public void GetAvailSportsAsync(object userState) {
            if ((this.GetAvailSportsOperationCompleted == null)) {
                this.GetAvailSportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailSportsOperationCompleted);
            }
            this.InvokeAsync("GetAvailSports", new object[0], this.GetAvailSportsOperationCompleted, userState);
        }
        
        private void OnGetAvailSportsOperationCompleted(object arg) {
            if ((this.GetAvailSportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailSportsCompleted(this, new GetAvailSportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://msiggi.de/Sportsdata/Webservices/GetAvailLeaguesBySports", RequestNamespace="http://msiggi.de/Sportsdata/Webservices", ResponseNamespace="http://msiggi.de/Sportsdata/Webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public League[] GetAvailLeaguesBySports(int sportID) {
            object[] results = this.Invoke("GetAvailLeaguesBySports", new object[] {
                        sportID});
            return ((League[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailLeaguesBySportsAsync(int sportID) {
            this.GetAvailLeaguesBySportsAsync(sportID, null);
        }
        
        /// <remarks/>
        public void GetAvailLeaguesBySportsAsync(int sportID, object userState) {
            if ((this.GetAvailLeaguesBySportsOperationCompleted == null)) {
                this.GetAvailLeaguesBySportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailLeaguesBySportsOperationCompleted);
            }
            this.InvokeAsync("GetAvailLeaguesBySports", new object[] {
                        sportID}, this.GetAvailLeaguesBySportsOperationCompleted, userState);
        }
        
        private void OnGetAvailLeaguesBySportsOperationCompleted(object arg) {
            if ((this.GetAvailLeaguesBySportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailLeaguesBySportsCompleted(this, new GetAvailLeaguesBySportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class League {
        
        private int leagueIDField;
        
        private int leagueSportIDField;
        
        private string leagueNameField;
        
        private string leagueShortcutField;
        
        private string leagueSaisonField;
        
        /// <remarks/>
        public int leagueID {
            get {
                return this.leagueIDField;
            }
            set {
                this.leagueIDField = value;
            }
        }
        
        /// <remarks/>
        public int leagueSportID {
            get {
                return this.leagueSportIDField;
            }
            set {
                this.leagueSportIDField = value;
            }
        }
        
        /// <remarks/>
        public string leagueName {
            get {
                return this.leagueNameField;
            }
            set {
                this.leagueNameField = value;
            }
        }
        
        /// <remarks/>
        public string leagueShortcut {
            get {
                return this.leagueShortcutField;
            }
            set {
                this.leagueShortcutField = value;
            }
        }
        
        /// <remarks/>
        public string leagueSaison {
            get {
                return this.leagueSaisonField;
            }
            set {
                this.leagueSaisonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Sports {
        
        private int sportsIDField;
        
        private string sportsNameField;
        
        /// <remarks/>
        public int sportsID {
            get {
                return this.sportsIDField;
            }
            set {
                this.sportsIDField = value;
            }
        }
        
        /// <remarks/>
        public string sportsName {
            get {
                return this.sportsNameField;
            }
            set {
                this.sportsNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Group {
        
        private string groupNameField;
        
        private int groupOrderIDField;
        
        private int groupIDField;
        
        /// <remarks/>
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public int groupOrderID {
            get {
                return this.groupOrderIDField;
            }
            set {
                this.groupOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public int groupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Team {
        
        private int teamIDField;
        
        private string teamNameField;
        
        private string teamIconURLField;
        
        /// <remarks/>
        public int teamID {
            get {
                return this.teamIDField;
            }
            set {
                this.teamIDField = value;
            }
        }
        
        /// <remarks/>
        public string teamName {
            get {
                return this.teamNameField;
            }
            set {
                this.teamNameField = value;
            }
        }
        
        /// <remarks/>
        public string teamIconURL {
            get {
                return this.teamIconURLField;
            }
            set {
                this.teamIconURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Fussballdaten {
        
        private int spielIDField;
        
        private int spieltagField;
        
        private System.DateTime spieldatumField;
        
        private string team1Field;
        
        private string team2Field;
        
        private int ergebnisTeam1Field;
        
        private int ergebnisTeam2Field;
        
        private System.DateTime lastUpdateField;
        
        /// <remarks/>
        public int SpielID {
            get {
                return this.spielIDField;
            }
            set {
                this.spielIDField = value;
            }
        }
        
        /// <remarks/>
        public int Spieltag {
            get {
                return this.spieltagField;
            }
            set {
                this.spieltagField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Spieldatum {
            get {
                return this.spieldatumField;
            }
            set {
                this.spieldatumField = value;
            }
        }
        
        /// <remarks/>
        public string Team1 {
            get {
                return this.team1Field;
            }
            set {
                this.team1Field = value;
            }
        }
        
        /// <remarks/>
        public string Team2 {
            get {
                return this.team2Field;
            }
            set {
                this.team2Field = value;
            }
        }
        
        /// <remarks/>
        public int ErgebnisTeam1 {
            get {
                return this.ergebnisTeam1Field;
            }
            set {
                this.ergebnisTeam1Field = value;
            }
        }
        
        /// <remarks/>
        public int ErgebnisTeam2 {
            get {
                return this.ergebnisTeam2Field;
            }
            set {
                this.ergebnisTeam2Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Location {
        
        private int locationIDField;
        
        private string locationCityField;
        
        private string locationStadiumField;
        
        /// <remarks/>
        public int locationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
            }
        }
        
        /// <remarks/>
        public string locationCity {
            get {
                return this.locationCityField;
            }
            set {
                this.locationCityField = value;
            }
        }
        
        /// <remarks/>
        public string locationStadium {
            get {
                return this.locationStadiumField;
            }
            set {
                this.locationStadiumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Goal {
        
        private int goalIDField;
        
        private System.Nullable<int> goalScoreTeam1Field;
        
        private System.Nullable<int> goalScoreTeam2Field;
        
        private System.Nullable<int> goalMatchMinuteField;
        
        private int goalGetterIDField;
        
        private string goalGetterNameField;
        
        private System.Nullable<bool> goalPenaltyField;
        
        private System.Nullable<bool> goalOwnGoalField;
        
        private System.Nullable<bool> goalOvertimeField;
        
        /// <remarks/>
        public int goalID {
            get {
                return this.goalIDField;
            }
            set {
                this.goalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> goalScoreTeam1 {
            get {
                return this.goalScoreTeam1Field;
            }
            set {
                this.goalScoreTeam1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> goalScoreTeam2 {
            get {
                return this.goalScoreTeam2Field;
            }
            set {
                this.goalScoreTeam2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> goalMatchMinute {
            get {
                return this.goalMatchMinuteField;
            }
            set {
                this.goalMatchMinuteField = value;
            }
        }
        
        /// <remarks/>
        public int goalGetterID {
            get {
                return this.goalGetterIDField;
            }
            set {
                this.goalGetterIDField = value;
            }
        }
        
        /// <remarks/>
        public string goalGetterName {
            get {
                return this.goalGetterNameField;
            }
            set {
                this.goalGetterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> goalPenalty {
            get {
                return this.goalPenaltyField;
            }
            set {
                this.goalPenaltyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> goalOwnGoal {
            get {
                return this.goalOwnGoalField;
            }
            set {
                this.goalOwnGoalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> goalOvertime {
            get {
                return this.goalOvertimeField;
            }
            set {
                this.goalOvertimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class matchResult {
        
        private string resultNameField;
        
        private int pointsTeam1Field;
        
        private int pointsTeam2Field;
        
        private int resultOrderIDField;
        
        /// <remarks/>
        public string resultName {
            get {
                return this.resultNameField;
            }
            set {
                this.resultNameField = value;
            }
        }
        
        /// <remarks/>
        public int pointsTeam1 {
            get {
                return this.pointsTeam1Field;
            }
            set {
                this.pointsTeam1Field = value;
            }
        }
        
        /// <remarks/>
        public int pointsTeam2 {
            get {
                return this.pointsTeam2Field;
            }
            set {
                this.pointsTeam2Field = value;
            }
        }
        
        /// <remarks/>
        public int resultOrderID {
            get {
                return this.resultOrderIDField;
            }
            set {
                this.resultOrderIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://msiggi.de/Sportsdata/Webservices")]
    public partial class Matchdata {
        
        private int matchIDField;
        
        private System.DateTime matchDateTimeField;
        
        private string timeZoneIDField;
        
        private System.DateTime matchDateTimeUTCField;
        
        private int groupIDField;
        
        private int groupOrderIDField;
        
        private string groupNameField;
        
        private int leagueIDField;
        
        private string leagueNameField;
        
        private string leagueSaisonField;
        
        private string nameTeam1Field;
        
        private string nameTeam2Field;
        
        private int idTeam1Field;
        
        private int idTeam2Field;
        
        private string iconUrlTeam1Field;
        
        private string iconUrlTeam2Field;
        
        private int pointsTeam1Field;
        
        private int pointsTeam2Field;
        
        private System.DateTime lastUpdateField;
        
        private bool matchIsFinishedField;
        
        private matchResult[] matchResultsField;
        
        private Goal[] goalsField;
        
        private Location locationField;
        
        private System.Nullable<int> numberOfViewersField;
        
        /// <remarks/>
        public int matchID {
            get {
                return this.matchIDField;
            }
            set {
                this.matchIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime matchDateTime {
            get {
                return this.matchDateTimeField;
            }
            set {
                this.matchDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZoneID {
            get {
                return this.timeZoneIDField;
            }
            set {
                this.timeZoneIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime matchDateTimeUTC {
            get {
                return this.matchDateTimeUTCField;
            }
            set {
                this.matchDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public int groupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public int groupOrderID {
            get {
                return this.groupOrderIDField;
            }
            set {
                this.groupOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public int leagueID {
            get {
                return this.leagueIDField;
            }
            set {
                this.leagueIDField = value;
            }
        }
        
        /// <remarks/>
        public string leagueName {
            get {
                return this.leagueNameField;
            }
            set {
                this.leagueNameField = value;
            }
        }
        
        /// <remarks/>
        public string leagueSaison {
            get {
                return this.leagueSaisonField;
            }
            set {
                this.leagueSaisonField = value;
            }
        }
        
        /// <remarks/>
        public string nameTeam1 {
            get {
                return this.nameTeam1Field;
            }
            set {
                this.nameTeam1Field = value;
            }
        }
        
        /// <remarks/>
        public string nameTeam2 {
            get {
                return this.nameTeam2Field;
            }
            set {
                this.nameTeam2Field = value;
            }
        }
        
        /// <remarks/>
        public int idTeam1 {
            get {
                return this.idTeam1Field;
            }
            set {
                this.idTeam1Field = value;
            }
        }
        
        /// <remarks/>
        public int idTeam2 {
            get {
                return this.idTeam2Field;
            }
            set {
                this.idTeam2Field = value;
            }
        }
        
        /// <remarks/>
        public string iconUrlTeam1 {
            get {
                return this.iconUrlTeam1Field;
            }
            set {
                this.iconUrlTeam1Field = value;
            }
        }
        
        /// <remarks/>
        public string iconUrlTeam2 {
            get {
                return this.iconUrlTeam2Field;
            }
            set {
                this.iconUrlTeam2Field = value;
            }
        }
        
        /// <remarks/>
        public int pointsTeam1 {
            get {
                return this.pointsTeam1Field;
            }
            set {
                this.pointsTeam1Field = value;
            }
        }
        
        /// <remarks/>
        public int pointsTeam2 {
            get {
                return this.pointsTeam2Field;
            }
            set {
                this.pointsTeam2Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
            }
        }
        
        /// <remarks/>
        public bool matchIsFinished {
            get {
                return this.matchIsFinishedField;
            }
            set {
                this.matchIsFinishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public matchResult[] matchResults {
            get {
                return this.matchResultsField;
            }
            set {
                this.matchResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Goal[] goals {
            get {
                return this.goalsField;
            }
            set {
                this.goalsField = value;
            }
        }
        
        /// <remarks/>
        public Location location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumberOfViewers {
            get {
                return this.numberOfViewersField;
            }
            set {
                this.numberOfViewersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAvailLeaguesCompletedEventHandler(object sender, GetAvailLeaguesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailLeaguesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailLeaguesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public League[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((League[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetNextMatchCompletedEventHandler(object sender, GetNextMatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNextMatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNextMatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastMatchCompletedEventHandler(object sender, GetLastMatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastMatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastMatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCurrentGroupOrderIDCompletedEventHandler(object sender, GetCurrentGroupOrderIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentGroupOrderIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentGroupOrderIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMatchdataByGroupLeagueSaisonCompletedEventHandler(object sender, GetMatchdataByGroupLeagueSaisonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchdataByGroupLeagueSaisonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchdataByGroupLeagueSaisonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMatchdataByLeagueDateTimeCompletedEventHandler(object sender, GetMatchdataByLeagueDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchdataByLeagueDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchdataByLeagueDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMatchdataByTeamsCompletedEventHandler(object sender, GetMatchdataByTeamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchdataByTeamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchdataByTeamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMatchdataByLeagueSaisonCompletedEventHandler(object sender, GetMatchdataByLeagueSaisonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchdataByLeagueSaisonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchdataByLeagueSaisonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMatchdataByGroupLeagueSaisonJSONCompletedEventHandler(object sender, GetMatchdataByGroupLeagueSaisonJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchdataByGroupLeagueSaisonJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchdataByGroupLeagueSaisonJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFusballdatenCompletedEventHandler(object sender, GetFusballdatenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFusballdatenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFusballdatenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Fussballdaten[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Fussballdaten[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetMatchByMatchIDCompletedEventHandler(object sender, GetMatchByMatchIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchByMatchIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchByMatchIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Matchdata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Matchdata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTeamsByLeagueSaisonCompletedEventHandler(object sender, GetTeamsByLeagueSaisonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamsByLeagueSaisonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamsByLeagueSaisonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Team[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Team[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAvailGroupsCompletedEventHandler(object sender, GetAvailGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Group[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Group[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAvailSportsCompletedEventHandler(object sender, GetAvailSportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailSportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailSportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sports[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sports[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAvailLeaguesBySportsCompletedEventHandler(object sender, GetAvailLeaguesBySportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailLeaguesBySportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailLeaguesBySportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public League[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((League[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591