//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGAN_Svc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundsOfActualSeason
    {
        public System.Guid ID { get; set; }
        public System.Guid SeasonID { get; set; }
        public int Spieltag { get; set; }
    }
}
